Repository liip/drifter, pull requests merged in 2019-01, with the labels that each got.

#244 Node.js: enable version 9 to 11 and makes 10 the default
  CHANGELOG.md
  docs/roles/others.rst
  provisioning/roles/nodejs/defaults/main.yml
Labels: role: nodejs

#238 Remove and change deprecated ansible instructions
  CHANGELOG.md
  Vagrantfile.dist
  playground/Vagrantfile
  playground/parameters.yml
  provisioning/playbook.yml.dist
  provisioning/roles/base/tasks/main.yml
  provisioning/roles/chrome/tasks/main.yml
  provisioning/roles/compass/tasks/main.yml
  provisioning/roles/composer/tasks/main.yml
  provisioning/roles/firefox/tasks/main.yml
  provisioning/roles/git/tasks/main.yml
  provisioning/roles/gitlabci/tasks/main.yml
  provisioning/roles/java/tasks/main.yml
  provisioning/roles/jdk/tasks/main.yml
  provisioning/roles/maven/tasks/main.yml
  provisioning/roles/memcached/tasks/main.yml
  provisioning/roles/mysql/tasks/main.yml
  provisioning/roles/nginx/templates/django-site.j2
  provisioning/roles/nginx/templates/drupal6-site.j2
  provisioning/roles/nginx/templates/drupal7-site.j2
  provisioning/roles/nginx/templates/drupal8-site.j2
  provisioning/roles/nginx/templates/php-site.j2
  provisioning/roles/nginx/templates/rails-site.j2
  provisioning/roles/nginx/templates/silex-site.j2
  provisioning/roles/nginx/templates/symfony2-site.j2
  provisioning/roles/nginx/templates/symfony4-site.j2
  provisioning/roles/nodejs/tasks/main.yml
  provisioning/roles/openldap/tasks/main.yml
  provisioning/roles/phantomjs/tasks/main.yml
  provisioning/roles/phive/tasks/main.yml
  provisioning/roles/php-apache/tasks/main.yml
  provisioning/roles/php-xdebug/tasks/main.yml
  provisioning/roles/php/tasks/debian-repo.yml
  provisioning/roles/php/tasks/main.yml
  provisioning/roles/php/tasks/ubuntu-repo.yml
  provisioning/roles/php/tasks/wheezy-php5.yml
  provisioning/roles/python/tasks/main.yml
  provisioning/roles/rabbitmq/tasks/main.yml
  provisioning/roles/redis/tasks/main.yml
  provisioning/roles/ruby/tasks/main.yml
  provisioning/roles/solr/defaults/main.yml
  provisioning/roles/solr/tasks/main.yml
  provisioning/roles/ssh/tasks/main.yml
  provisioning/roles/supervisor/handlers/main.yml
  provisioning/roles/virtualenv/tasks/main.yml
  provisioning/roles/xvfb/tasks/main.yml
Labels: area: core

#255 Drop support for Debian Wheezy
  CHANGELOG.md
  docs/roles/databases.rst
  docs/roles/others.rst
  docs/roles/php.rst
  provisioning/roles/nodejs/defaults/main.yml
  provisioning/roles/php/tasks/debian-repo.yml
  provisioning/roles/php/tasks/main.yml
  provisioning/roles/php/tasks/wheezy-php5.yml
  provisioning/roles/python/tasks/main.yml
  provisioning/roles/supervisor/defaults/main.yml
  provisioning/roles/supervisor/tasks/main.yml
  provisioning/roles/supervisor/tasks/wheezy.yml
Labels: type: clean-up
